#!/bin/sh

if [ -z "${NORTHPIKE_AGENT_HOME}" ]
then
  echo "NORTHPIKE_AGENT_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${NORTHPIKE_AGENT_HOME}/lib" \
-m com.io7m.northpike.agent.main/com.io7m.northpike.agent.main.NPAgentMain \
"$@"
