#!/bin/sh

if [ -z "${NORTHPIKE_HOME}" ]
then
  echo "NORTHPIKE_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${NORTHPIKE_HOME}/lib" \
-m com.io7m.northpike.server.main/com.io7m.northpike.server.main.NPServerMain \
"$@"
