#!/bin/sh

if [ -z "${NORTHPIKE_WORKEXEC_HOME}" ]
then
  echo "NORTHPIKE_WORKEXEC_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${NORTHPIKE_WORKEXEC_HOME}/lib" \
-m com.io7m.northpike.agent.workexec.main/com.io7m.northpike.agent.workexec.main.NPWorkExecMain \
"$@"
